theme: jekyll-theme-cayman
title: "Digital Product Management by Professor Alex Cowan, UVA Darden School of Business via Coursera"
description: "Study Notes"

# Build settings
markdown: kramdown
kramdown:
   math_engine: mathjax
